CREATE TABLE student (
	stId INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT "id",
	stName VARCHAR ( 50 ) NOT NULL COMMENT "姓名",
	stAge INT ( 2 ) NOT NULL COMMENT "年龄",
	stPhoneNo VARCHAR ( 11 ) DEFAULT "000000" COMMENT "手机",
	stGender VARCHAR ( 4 ) NOT NULL COMMENT "性别",
	stClass VARCHAR ( 30 ) NOT NULL COMMENT "班级",
	stHome VARCHAR ( 100 ) COMMENT "家庭住址",
	PRIMARY KEY ( stId ) 
) ENGINE = INNODB AUTO_INCREMENT = 100 DEFAULT CHARSET = utf8;