CREATE TABLE teacher (
	teId INT ( 11 ) NOT NULL AUTO_INCREMENT COMMENT "id",
	teName VARCHAR ( 50 ) NOT NULL COMMENT "姓名",
	teAge INT ( 2 ) NOT NULL COMMENT "年龄",
	tePhoneNo VARCHAR ( 11 ) NOT NULL DEFAULT "000000" COMMENT "手机",
	teGender VARCHAR ( 4 ) NOT NULL COMMENT "性别",
	teClass VARCHAR ( 30 ) NOT NULL COMMENT "教授班级",
	teCourse VARCHAR ( 20 ) NOT NULL COMMENT "教授科目",
	teWorkTime INT ( 2 ) COMMENT "工作年限",
	PRIMARY KEY ( teId )
) ENGINE = INNODB AUTO_INCREMENT = 500 DEFAULT CHARSET = utf8;